name: Ping Supabase

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm ci
      - name: Ping Supabase
        run: curl -X GET https://purplecat-stayzen.vercel.app/api/supabase
